# -*- mode: conf; -*-

top-title: 诗人 图书馆管理员

author:
  name: adomikao
  email: adomikao@gmail.com
  github: adomikao

markdown: kramdown
permalink: none
baseurl: /mzd
img_url: /mzd/images
font_url: /mzd/fonts

collections:
  characters:
    output: true
